name: test workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
    paths:
      - 'my-app/**'

jobs:
  unit-test-and-eslint:
    name: Run unit test
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js (16)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Package Install
        working-directory: ./my-app
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Eslint
        working-directory: ./my-app
        run: yarn run lint

      - name: Run unit test
        working-directory: ./my-app
        run: yarn run test
